from django.urls import path
from . import views
from .views import create_payment_intent, confirm_payment


urlpatterns = [
    path('', views.index, name='index'),
    path('category/', views.category_view, name='category'),
    path('header/', views.header_view, name='header'),
    path('footer/', views.footer, name='footer'),
    path('food/',views.food_view,name='food'),
    path('makeup/', views.makeup_page, name='makeup_page'),
    path('perfumes/', views.perfumes, name='perfumes'),
    path('shoes/',views.shoes, name='shoes'),
    path('cleaning/',views.cleaning, name='cleaning'),
    path('clothing/',views.clothing, name='clothing'),
    path('games/',views.games, name='games'),
    path('furnitures/',views.furnitures, name='furnitures'),
    path('Beverage/',views.Beverage, name='Beverage'),
    path('seafoodplatter/', views.seafood_platter_view, name='seafood_platter'),
    path('salmon/', views.Salmon, name='Salmon'),
    path('chicken/',views.Chicken,name='Chicken'),
    path('sushi/',views.Sushi,name='Sushi'),
    path('steak/',views.Steak,name='Steak'),
    path('shawarma/',views.Shawarma,name='Shawarma'),
    path('sandwich/',views.Sandwich,name='Sandwich'),
    path('burger/',views.Burger,name='Burger'),
    path('croissant/',views.Croissant,name='Croissant'),
    path('jarcake/',views.JarCake,name='JarCake'),
    path('christmascake/',views.christmascake,name='christmascake'),
    path('matt/',views.matt,name='matt'),
    path('peptide/',views.peptide,name='peptide'),
    path('concealer/',views.concealer,name='concealer'),
    path('highlighter/',views.highlighter,name='highlighter'),
    path('shadow/',views.shadow,name='shadow'),
    path('mascara/',views.mascara,name='mascara'),
    path('cleanser/',views.cleanser,name='cleanser'),
    path('lotion/',views.lotion,name='lotion'),
    path('serum/',views.serum,name='serum'),
    path('Beauty/',views.Beauty,name='Beauty'),
    path('Lipshade/',views.Lipshade,name='Lipshade'),
    path('remover/',views.remover,name='remover'),
    path('moonlight/',views.moonlight,name='moonlight'),
    path('carolina/',views.carolina,name='carolina'),
    path('chanel/',views.chanel,name='chanel'),
    path('wildflower/',views.wildflower,name='wildflower'),
    path('bleu/',views.bleu,name='bleu'),
    path('gucci/',views.gucci,name='gucci'),
    path('vanilla/',views.vanilla,name='vanilla'),
    path('Perfumecollection/',views.Perfumecollection,name='Perfumecollection'),
    path('lux/',views.lux,name='lux'),
    path('blackheels/',views.blackheels,name='blackheels'),
    path('whiteheels/',views.whiteheels,name='whiteheels'),
    path('elegantflats/',views.elegantflats,name='elegantflats'),
    path('ribbon/',views.ribbon,name='ribbon'),
    path('officeheels/',views.officeheels,name='officeheels'),
    path('sneaker/',views.sneakers,name='sneakers'),
    path('lowheels/',views.lowheels,name='lowheels'),
    path('phillips/',views.phillips,name='phillips'),
    path('brooms/',views.brooms,name='brooms'),
    path('glasscleaner/',views.glasscleaner,name='glasscleaner'),
    path('glasswiper/',views.glasswiper,name='glasswiper'),
    path('gloves/',views.gloves,name='gloves'),
    path('dishsoap/',views.dishsoap,name='dishsoap'),
    path('summer/',views.summer,name='summer'),
    path('gown/',views.gown,name='gown'),
    path('denims/',views.denims,name='denims'),
    path('officeattire/',views.officeattire,name='officeattire'),
    path('jeans/',views.jeans,name='jeans'),
    path('formalattire/',views.formalattire,name='formalattire'),
    path('PS5/',views.PS5,name='PS5'),
    path('chair/',views.chair,name='chair'),
    path('keyboard/',views.keyboard,name='keyboard'),
    path('headset/',views.headset,name='headset'),
    path('controller/',views.controller,name='controller'),
    path('gamingpackage/',views.gamingpackage,name='gamingpackage'),
    path('pc/',views.pc,name='pc'),
    path('singlesofa/',views.singlesofa,name='singlesofa'),
    path('bingbang/',views.bingbang,name='bingbang'),
    path('coffeetable/',views.coffeetable,name='coffeetable'),
    path('desk/',views.desk,name='desk'),
    path('livingsofa/',views.livingsofa,name='livingsofa'),
    path('whitebed/',views.whitebed,name='whitebed'),
    path('netany/',views.netany,name='netany'),
    path('bamboo/',views.bamboo,name='bamboo'),
    path('decemera/',views.decemera,name='decemera'),
    path('luxu/',views.luxu,name='luxu'),
    path('minibottles/',views.minibottles,name='minibottles'),
    path('bottles/',views.bottles,name='bottles'),
    path('glaver/',views.glaver,name='glaver'),

    path('search/', views.product_search, name='product_search'),






    path('coupon1/', views.Coupon1, name='Coupon1'),
    path('coupon2/', views.Coupon2, name='Coupon2'),
    path('coupon3/',views.Coupon3,name='Coupon3'),
    path('deals/',views.Deals,name='Deals'),
    path('about-us/',views.AboutUs,name='AboutUs'),
    path('contact/',views.Contact,name='Contact'),
    path('submit-complaint/', views.submit_complaint, name='submit_complaint'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.view_cart, name='view_cart'),
    path('remove-from-cart/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('add-to-wishlist/<int:product_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/', views.view_wishlist, name='wishlist'),
    path('remove-from-wishlist/<int:product_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('confirm-payment/', confirm_payment, name='confirm_payment'),
    path('process_checkout/', views.process_checkout, name='process_checkout'),
    

    path('checkout/', views.checkout, name='checkout'),
    path('process_checkout/', views.process_checkout, name='process_checkout'),
    path('payment/', views.payment_page, name='payment_page'),  # Updated URL pattern
    path('finishing/', views.finishing, name='finishing'),
    path('payment_failed/', views.payment_failed, name='payment_failed'),
    path('process_payment/', views.process_payment, name='process_payment'),  # Add this line


    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
]